export const GET_CHANNEL_LIST_REQUEST = 'GET_CHANNEL_LIST_REQUEST'
export const GET_CHANNEL_LIST_SUCCESS = 'GET_CHANNEL_LIST_SUCCESS'
export const GET_CHANNEL_LIST_FAIL = 'GET_CHANNEL_LIST_FAIL'

export const GET_CHANNEL_INFO_SUCCESS = 'GET_CHANNEL_INFO_SUCCESS'
export const GET_CHANNEL_INFO_FAIL = 'GET_CHANNEL_INFO_FAIL'
export const SET_ACTIVE_CHANNEL = 'SET_ACTIVE_CHANNEL'

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'

export const GET_PRIVATE_CHANNEL_LIST_REQUEST =
  'GET_PRIVATE_CHANNEL_LIST_REQUEST'
export const GET_PRIVATE_CHANNEL_LIST_SUCCESS =
  'GET_PRIVATE_CHANNEL_LIST_SUCCESS'
export const GET_PRIVATE_CHANNEL_LIST_FAIL = 'GET_PRIVATE_CHANNEL_LIST_FAIL'
