export const USER_LOG_IN_REQUEST = 'USER_LOG_IN_REQUEST'
export const USER_LOG_IN_SUCCESS = 'USER_LOG_IN_SUCCESS'
export const USER_LOG_IN_FAIL = 'USER_LOG_IN_FAIL'
export const USER_SIGN_OUT = 'USER_SIGN_OUT'
